W7D2/MusicApp/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:create, :new, :show]
  resource :session, only: [:create, :new, :destroy]
  resources :bands, only: [:index, :create, :new, :edit, :show, :update, :destroy]
end   

W7D2/MusicApp/app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :bigint           not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Band < ApplicationRecord
    validates :name, presence: true

    
end

W7D2/MusicApp/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  session_token   :string           not null
#  email           :string           not null
#  password_digest :string           not null
#
class User < ApplicationRecord

    validates :session_token, :email, presence: true, uniqueness: true
    validates :password_digest, presence: { message: 'Password can\t blank'}
    validates :password, length: {minimum: 6, allow_nil: true}

    after_initialize :ensure_session_token

    attr_reader :password
    
    def self.generate_session_token
        SecureRandom::urlsafe_base64(16)
    end

    def self.find_by_credentials(email, password)
        user = User.find_by(email: email)
        return nil if user.nil?

        user.is_password?(password) ? user : nil 
    end

    def reset_session_token!
        self.session_token = User.generate_session_token
        self.save!
        self.session_token
    end

    def password=(password)
        @password = password
        self.password_digest =  BCrypt::Password.create(password)
    end

    def is_password?(password)
        BCrypt::Password.new(self.password_digest).is_password?(password)
    end

    private

    def ensure_session_token
        self.session_token ||= User.generate_session_token
    end

end

W7D2/MusicApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user
    helper_method :logged_in?

    private

        def current_user
            return nil unless session[:session_token]
            @current_user ||= User.find_by(session_token: session[:session_token])
        end
        
        def logged_in?
            !current_user.nil?
        end

        def login_user!(user)
            session[:session_url] = user.reset_session_token!
        end

        def logout_user!
            current_user.reset_session_token
            session[:session_token] = nil
        end
end

W7D2/MusicApp/app/controllers/bands_controller.rb
class BandsController < ApplicationController

    def index
       @bands = Band.all
       render :index
    end

    def create
        @band = Band.new(band_params)
        if @band.save
            redirect_to band_url(@band)
        else
            # debugger
            flash.now[:errors] = @band.errors.full_messages
            render :new
        end
    end

    def new
        @band = Band.new
        render :new
    end

    def edit
        @band = Band.find(params[:id])
        render :edit
    end

    def show
        @band = Band.find(params[:id])
        render :show
    end

    def update
        @band = Band.find(params[:id])

        if @band.update(band_params) 
            redirect_to band_url(@band)
        else
            flash.now[:errors] = @band.errors.full_messages
            render :edit
        end
        
    end

    def destroy
        @band = Band.find(params[:id])
        @band.destroy
        redirect_to bands_url
    end

    private
    def band_params
        params.require(:band).permit(:name)
    end
end

W7D2/MusicApp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    # before_action :require_no_user!, only: %i(create new)
    # debugger
    def create
        user = User.find_by_credentials(params[:user][:email], params[:user][:password])
        # debugger
        if user.nil?
            flash.now[:errors] = ['Incorrect Username and/or password']
            render :new
        else
            # debugger
            login_user!(user)
            render json: user
        end
    end
    
    def destroy
        logout_user!
        redirect_to new_session_url
    end

    def new
        render :new
    end
end

W7D2/MusicApp/app/controllers/users_controller.rb
class UsersController < ApplicationController

    def show
        @user = User.find(params[:id])
        render :show
    end

    def create
        @user = User.new(user_params)
        if @user.save
            login_user!(@user)
            render json: @user
        else
            flash.now[:errors] = @user.errors.full_messages
            render :new
        end
    end

    def new
        @user = User.new
        render :new
    end

    private 
    def user_params
        params.require(:user).permit(:email, :password)
    end
end

W7D2/MusicApp/app/helpers/bands_helper.rb
module BandsHelper
end

W7D2/MusicApp/app/views/bands/_form.html.erb
<% if is_edit%>
    <% action = band_url(band)%>
    <% button_text = "Edit your band!"%>
<% else %>
    <% action = bands_url %>
    <% button_text = "Make a New Band!"%>
<% end %>

<form action="<%= action %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <% if is_edit %>
        <input type="hidden" name="_method" value="patch">
    <% end %>

    <label for="name">Name</label>
    <input id="name" type="text" name="band[name]" value ="<%= band.name%>">

    <input type="submit" value="<%= button_text%>">
</form>

W7D2/MusicApp/app/views/bands/edit.html.erb
<h1>Edit <%= @band.name %></h1>

<%= render "form", is_edit: true, band: @band %>

W7D2/MusicApp/app/views/bands/index.html.erb
<h1>All the bands!</h1>

<ul>
<% @bands.each do |band| %>
    <li><%= band.name %></li>
<% end %>

</ul>

W7D2/MusicApp/app/views/bands/new.html.erb
<h1>Make a New Band!</h1>

<%= render "form", is_edit: false, band: @band %>

W7D2/MusicApp/app/views/bands/show.html.erb
<h1><%= @band.name%></h1>

<a href="<%= edit_band_url(@band) %>">Edit Band</a>

<form action="<%= band_url(@band) %>" method="POST">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="submit" value="Destroy Band">
</form>

<a href=" <%= bands_url %>"> All bands</a>

W7D2/MusicApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1 class='main-logo'>Music App</h1>
      <nav> 
        <div>
        <% if current_user.nil? %>
          <a href="<%= new_session_url %>">Log In</a>
          <a href="<%= new_user_url %>">Sign Up</a>
        <% else %>
          <p> Logged in as: <%= current_user.email %></p>
            <form action=<%= session_url %> method='post'>
              <input type="hidden" name='_method' value='delete'>
              <input type='hidden' name='authenticity_token' value="<%= form_authenticity_token %>">
              <input type="submit" value= "Sign Out">
         </form>
        </div>
      </nav>
      <% end %>
    <%= yield %>
  </body>
</html>

W7D2/MusicApp/app/views/users/new.html.erb
<h1>New User</h1>

<form action="<%= users_url %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    
    <label for="email">Email</label>
    <input id="email" type="text" name="user[email]" value="<%= @user.email %>">

    <label for="password">Password</label>
    <input id="password" type="password" name="user[password]" value="<%= @user.password %>">
    
    <input type="submit" value="Login">

</form>

W7D2/MusicApp/app/views/users/show.html.erb
<h1>User Profile</h1>

<%= @user.email %>